

import os


DEFAULT_MAIL_FROM = os.environ['INFOMANIA_MAIL_FROM']
DEFAULT_MAIL_TO = os.environ['INFOMANIA_MAIL_TO'].split(',')
DEFAULT_MAIL_SUBJECT = '------- {} -------'

SMTP_SERVER = os.environ['INFOMANIA_SMTP_SERVER']
SMTP_USERNAME = os.environ['INFOMANIA_SMTP_USERNAME']
SMTP_PASSWORD = os.environ['INFOMANIA_SMTP_PASSWORD']